# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bind_rows_ <- function(dots, id = NULL) {
    .Call('coreSim_bind_rows_', PACKAGE = 'coreSim', dots, id)
}

rbind_list__impl <- function(dots) {
    .Call('coreSim_rbind_list__impl', PACKAGE = 'coreSim', dots)
}

